---
# defaults file for usegalaxy_eu.handy.os_setup
#
# Feature control
#
# Control which tasks are included,
enable_hostname: false
enable_powertools: false
enable_remap_user: false
enable_exclude_packages: false
enable_kernel_5: false
enable_pam_limits: false
enable_grub: false
enable_cgroups: false
enable_journald: false
enable_install_software: false

# pam_limits:
pam_limits:
  - domain: galaxy
    type: hard
    item: fsize
    value: "{{ 1 * 1024 * 1024 * 1024 }}"  # 1 TB

# kernel_5
kernel_5_package: kernel-lt

# exclude_package_from_update
exclude_packages:
  "/etc/yum.repos.d/epel.repo": "condor*,npm*"

# powertools
centos:
  path: /etc/yum.repos.d/CentOS-PowerTools.repo
  section: PowerTools
  version:
    - "8.1"
    - "8.2"

centos_linux:
  path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
  section: powertools
  version:
    - "8.3"
    - "8.4"
    - "8.5"

# remap_user
debug: false

# packages
software_groups_to_install:
  - admin
  - configuration
  - editors
  - utils
software_packages:
  admin:
    - htop
    - iotop
    - iftop
  apps:
    - singularity
  configuration:
    - ansible
  cgroups:
    - libcgroup
    - libcgroup-tools
  debug:
    - lsof
    - nmap
    - strace
    - tcpdump
  development:
    - "@development"
    - git
    - jq
    - patch
  editors:
    - vim
  fonts:
    - dejavu-fonts-common
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - fontconfig
    - fontconfig-devel
    - fontpackages-filesystem
    - liberation-fonts-common
    - liberation-sans-fonts
    - libfontenc
    - mesa-libGL
    - perl-Digest-MD5
    - perl-Digest-SHA
    - urw-fonts
    - xorg-x11-font-utils
  services:
    - {'package_name': 'at', 'daemon_name': 'atd'}
    - {'package_name': 'atop', 'daemon_name': 'atop'}
    - {'package_name': 'haveged', 'daemon_name': 'haveged'}
  terminals:
    - mosh
    - screen
    - tmux
  utils:
    - bind-utils
    - curl
    - libnsl
    - nfs-utils
    - tmpwatch
    - unzip
    - yum-utils
    - wget
