---
# defaults file for usegalaxy_eu.handy.os_setup
#
# Feature control
#
# Control which tasks are included,
enable_powertools: false
enable_remap_user: false

# powertools
centos:
  path: /etc/yum.repos.d/CentOS-PowerTools.repo
  section: PowerTools
  version:
    - "8.1"
    - "8.2"

centos_linux:
  path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
  section: powertools
  version:
    - "8.3"
    - "8.4"
    - "8.5"

# remap_user
debug: false
