CentOS:
  path: /etc/yum.repos.d/CentOS-PowerTools.repo
  section: PowerTools
  version:
    - "8.1"
    - "8.2"

CentOS_Linux:
  path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
  section: powertools
  version:
    - "8.3"
    - "8.4"
    - "8.5"
