---
- name: Install cgroups packages
  ansible.builtin.package:
    state: latest
    name: "{{ item }}"
  loop: "{{ software_packages.cgroups }}"

- name: enable and start cgconfig
  ansible.builtin.service:
    name: cgconfig
    enabled: true
    state: started
