---
# geerlingguy.repo-epel role doesn't enable PowerTools repository
# but EPEL packages may depend on packages from it
- name: Enable PowerTools repository
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled powertools
  when: ansible_os_family == "RedHat"
