---
# geerlingguy.repo-epel role doesn't enable PowerTools repository
# but EPEL packages may depend on packages from it
- name: Enable PowerTools repository
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled powertools
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version < "9"

# PowerTools is now called CRB
# Refer: https://wiki.rockylinux.org/rocky/repo/#notes-on-crb
- name: Enable CRB repository for RHEL9
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled crb
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"
