---
# Centos8 uses systemd-coredump:input for (999:999) which we need to map to
# the galaxy user/group.
#

- name: Check for input group
  ansible.builtin.command: grep -Fxq "input:x:999:" /etc/group
  ignore_errors: true
  register: check_input
  changed_when: false

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: check_input
  when: debug

- name: Replace in group file
  ansible.builtin.lineinfile:
    path: /etc/group
    regexp: 'input:x:999:'
    line: 'input:x:500:'
  when: 'not ansible_check_mode and check_input.rc == 0'

- name: Search and replace 999 group files
  ansible.builtin.command: "find / -mount -gid 999 -exec chgrp 500 '{}' +"
  ignore_errors: true
  when: check_input.rc == 0
  tags:
    - ignore_errors

- name: Check for coredump
  ansible.builtin.command: grep -Fxq "systemd-coredump:x:999:997:systemd Core Dumper:/:/sbin/nologin" /etc/passwd
  ignore_errors: true
  register: check_coredump
  changed_when: false

- name: Print return information from the previous task2
  ansible.builtin.debug:
    var: check_coredump
  when: debug

- name: Replace in passwd file
  ansible.builtin.lineinfile:
    path: /etc/passwd
    regexp: 'systemd-coredump:x:999:997:systemd Core Dumper:/:/sbin/nologin'
    line: 'systemd-coredump:x:500:997:systemd Core Dumper:/:/sbin/nologin'
  when: 'not ansible_check_mode and check_coredump.rc == 0'

- name: Search and replace 999 user files
  ansible.builtin.command: "find / -mount -uid 999 -exec chown 500 '{}' +"
  ignore_errors: true
  when: check_coredump.rc == 0
  tags:
    - ignore_errors
